### ISSUE TITLE
Celery error preventing tasks from running

### ISSUE THREAD

**Issue by jalewis** [9b/chirp#12]
The below error prevents new tasks from running.

[2018-05-21 15:30:00,101: WARNING/ForkPoolWorker-16]
/root/venv3/lib/python3.5/site-packages/pymongo/topology.py:149:
UserWarning: MongoClient opened before fork. Create MongoClient only after
forking. See PyMongo's documentation for details:
http://api.mongodb.org/python/current/faq.html#is-pymongo-fork-safe
   "MongoClient opened before fork. Create MongoClient only "
[2018-05-21 15:30:06,375: ERROR/ForkPoolWorker-16] Task
process_all_rss[64432368-c40a-4708-98c1-51e125ecdcf1] raised unexpected:
TypeError("the JSON object must be str, not 'bytes'",)
Traceback (most recent call last):
   File "/root/venv3/lib/python3.5/site-packages/celery/app/trace.py", line
374, in trace_task
     R = retval = fun(*args, **kwargs)
   File "/root/venv3/lib/python3.5/site-packages/celery/app/trace.py", line
629, in __protected_call__
     return self.run(*args, **kwargs)
   File "/root/chirp/app/tasks/__init__.py", line 104, in process_all_rss
     response = get_article(item, source['href'], reprocess)
   File "/root/chirp/app/tasks/__init__.py", line 75, in get_article
     article['sentiment'] = get_sentiment(text_content)
   File "/root/chirp/app/utils/helpers.py", line 117, in get_sentiment
     loaded = json.loads(response.content)
   File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
     s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by 9b** [comment]
Note to self: Likely culprit here is the sentiment request returning null results that then can't be loaded. Wrap the code block with an exception handler and ensure processing happens.
