### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by zabavnov** [9b/chirp#20]
I get this error when I try to add new monitor. I tried to install with Docker and without it, but an error was the same.
2018-06-15 16:18:57,052] ERROR in app: Exception on /monitors/add-monitor [POST]
Traceback (most recent call last):
 File "/var/chirp/venv3/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
   response = self.full_dispatch_request()
 File "/var/chirp/venv3/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/var/chirp/venv3/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/var/chirp/venv3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
   raise value
 File "/var/chirp/venv3/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
   rv = self.dispatch_request()
 File "/var/chirp/venv3/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/var/chirp/venv3/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
   return func(*args, **kwargs)
 File "/var/chirp/app/core/monitors.py", line 28, in add_monitor
   ga = GoogleAlerts(gdata['email'], gdata['password'])
TypeError: 'NoneType' object is not subscriptable

**Comment by 9b** [comment]
Did you add a username and password via the configuration setup?
